- name: Find VM with ludus_elastic_container as a role
  ansible.builtin.set_fact:
    ludus_elastic_vm: "{{ ludus | search_roles('ludus_elastic_container') }}"

- name: Fail if no elastic server VM found
  ansible.builtin.fail:
    msg: "Could not find any VM that has the *.ludus_elastic_container role in your config"
  when: ludus_elastic_vm is undefined or ludus_elastic_vm == None or ludus_elastic_vm | length == 0


- name: Set the token
  ansible.builtin.set_fact:
    ludus_elastic_fleet_server:
      "https://10.{{ range_second_octet }}.{{ ludus_elastic_vm.vlan }}.{{ ludus_elastic_vm.ip_last_octet }}:{{ ludus_elastic_fleet_port }}"
