- name: Get Elastic agents if needed
  run_once: true
  become: true
  block:
    - name: Create /opt/ludus/resources/ludus_elastic_agent directory if it doesn't exist
      ansible.builtin.file:
        path: "{{ ludus_install_directory }}/resources/ludus_elastic_agent"
        state: directory
        recurse: true
      delegate_to: localhost

    - name: Check if sysmon bin exists on Ludus for Windows targets
      ansible.builtin.stat:
        path: "{{ ludus_install_directory }}/resources/ludus_elastic_agent/sysmon.zip"
      register: windows_sysmon_exists
      delegate_to: localhost

    - name: Download the Windows sysmon bin if it doesn't exist
      ansible.builtin.get_url:
        url: "https://download.sysinternals.com/files/Sysmon.zip"
        dest: "{{ ludus_install_directory }}/resources/ludus_elastic_agent/sysmon.zip"
        mode: "0644"
      delegate_to: localhost
      when: not windows_sysmon_exists.stat.exists

    - name: Check if sysmon config exists on Ludus for Windows targets
      ansible.builtin.stat:
        path: "{{ ludus_install_directory }}/resources/ludus_elastic_agent/sysmon.xml"
      register: windows_sysmon_config_exists
      delegate_to: localhost

    - name: Download the Windows sysmon config if it doesn't exist
      ansible.builtin.get_url:
        url: "https://github.com/SwiftOnSecurity/sysmon-config/raw/refs/heads/master/sysmonconfig-export.xml"
        dest: "{{ ludus_install_directory }}/resources/ludus_elastic_agent/sysmon.xml"
        mode: "0644"
      delegate_to: localhost
      when: not windows_sysmon_config_exists.stat.exists

- name: Check if Sysmon is already installed
  ansible.windows.win_service_info:
    name: Sysmon
  register: sysmon_service

- name: Installing sysmon
  when: not sysmon_service.exists
  block:
    - name: Create sysmon install directory if it doesn't exist
      ansible.windows.win_file:
        path: "{{ ludus_elastic_sysmon_path }}"
        state: directory

    - name: Copy Sysmon.zip to the target
      ansible.windows.win_copy:
        src: "{{ ludus_install_directory }}/resources/ludus_elastic_agent/sysmon.zip"
        dest: "C:\\Ludus\\sysmon.zip"

    - name: Copy Sysmon.xml to the target
      ansible.windows.win_copy:
        src: "{{ ludus_install_directory }}/resources/ludus_elastic_agent/sysmon.xml"
        dest: "C:\\Program Files (x86)\\Sysmon\\sysmon.xml"

    - name: Unzip Sysmon.zip
      ansible.windows.win_powershell:
        script: |
          Expand-Archive -Path C:\Ludus\Sysmon.zip -DestinationPath "{{ ludus_elastic_sysmon_path }}"

    - name: Install Sysmon
      ansible.windows.win_shell: |
        & "{{ ludus_elastic_sysmon_path }}\Sysmon.exe" -accepteula -i "{{ ludus_elastic_sysmon_path }}\Sysmon.xml"
