---
# Load datas
- import_playbook: data.yml
  vars:
    data_path: "../ad/{{domain_name}}/data/"
  tags: 'data'
# set dns forwarder sans lab ==================================================================================================

- name: setup forwarders between trusted domains
  hosts: dc
  roles:
    - dnsforwarder