---
# Load datas
- import_playbook: data.yml
  vars:
    data_path: "../ad/{{ domain_name }}/data/"
  tags: 'data'

# Create a local user and password
- hosts: srv02
  tasks:
    - name: Ensure domain user 'jross' is in the Remote Desktop Users group
      ansible.windows.win_group_membership:
        name: Remote Desktop Users
        members: 
          - "SANDBOX\\jross"
        state: present
