---
# Load datas
- import_playbook: data.yml
  vars:
    data_path: "../ad/{{domain_name}}/data/"
  tags: 'data'


# 7. Enable PowerShell Script Block Logging (FINAL STEP - may break WinRM connectivity)
- name: Enable PowerShell Script Block Logging on Windows hosts
  hosts: domain
  roles:
    - powershell_logging

# --- LAT MOVE WORKSHOP MODS END HERE ---
