---
# Load datas
- import_playbook: data.yml
  vars:
    data_path: "../ad/{{domain_name}}/data/"
  tags: 'data'


#vuln logic goes here
- name: create entrypoint service account 
  hosts: dc02
  tasks:
    - name: add new service account to the domain administrator group 
      microsoft.ad.user:
        identity: svc_entrypoint
        password: ChangeMe1234!
        spn:
          set:
            - HTTP/ws01.sandbox.pwnzone.lab
        state: present
        groups:
          set: Domain Admins
        password_never_expires: true
  ignore_errors: true

# --------------------------------------------------------------------
# specifics vulns linked to the scenario are here
- name: plant fakespool server
  hosts: dc
  roles:
    - fakespooler

