---
# Load datas
- import_playbook: data.yml
  vars:
    data_path: "../ad/{{domain_name}}/data/"
  tags: 'data'


# . Create a scheduled task to load a privileged user's hash into memory on WS01
- name: Schedule task for privileged user hash on workstation
  hosts: srv02
  vars:
    # Ensure this user is a Domain Admin in sandbox.pwnzone.lab for the PtH/OpTH demos
    privileged_username: "adm_asnyder"
    # IMPORTANT: Replace with the actual password for adm_asnyder from your ad_data_sandbox.pwnzone.lab.yml
    privileged_password: "5u8p19T1jVqkW6K"
    privileged_domain: "sandbox.pwnzone.lab"
  roles:
    - privileged_user_task



# --- LAT MOVE WORKSHOP MODS END HERE ---
