---
# Load datas
- import_playbook: data.yml
  vars:
    data_path: "../ad/{{domain_name}}/data/"
  tags: 'data'
  
# set SANS magic vul specific scenario Details ==================================================================================================  
- name: make sure computer account passwords never expire because snapshots
  hosts: domain
  tasks:
    - name: set computer to never expire
      win_regedit:
        path: HKLM:\SYSTEM\CurrentControlSet\Services\Netlogon\Parameters
        name: DisablePasswordChange 
        data: 1
        type: dword


